// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
// ------------------------------------------------------------------------------
// Changes to this file must follow the http://aka.ms/api-review process.
// ------------------------------------------------------------------------------
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: System.Runtime.CompilerServices.ReferenceAssembly]
[assembly: System.Reflection.AssemblyTitle("System.CodeDom")]
[assembly: System.Reflection.AssemblyDescription("System.CodeDom")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.CodeDom")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("Microsoft® .NET Framework")]
[assembly: System.Reflection.AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersion("4.6.25519.03")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.6.25519.03 built by: dlab-DDVSOWINAGE013. Commit Hash: 8321c729934c0f8be754953439b88e6e1c120c24")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: System.Reflection.AssemblyMetadata("Serviceable", "True")]
[assembly: System.Reflection.AssemblyMetadata("PreferInbox", "True")]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.CSharp.CSharpCodeProvider))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.VisualBasic.VBCodeProvider))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeArgumentReferenceExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeArrayCreateExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeArrayIndexerExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeAssignStatement))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeAttachEventStatement))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeAttributeArgument))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeAttributeArgumentCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeAttributeDeclaration))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeAttributeDeclarationCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeBaseReferenceExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeBinaryOperatorExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeBinaryOperatorType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeCastExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeCatchClause))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeCatchClauseCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeChecksumPragma))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeComment))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeCommentStatement))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeCommentStatementCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeCompileUnit))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeConditionStatement))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeConstructor))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeDefaultValueExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeDelegateCreateExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeDelegateInvokeExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeDirectionExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeDirective))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeDirectiveCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeEntryPointMethod))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeEventReferenceExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeExpressionCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeExpressionStatement))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeFieldReferenceExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeGotoStatement))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeIndexerExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeIterationStatement))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeLabeledStatement))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeLinePragma))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeMemberEvent))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeMemberField))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeMemberMethod))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeMemberProperty))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeMethodInvokeExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeMethodReferenceExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeMethodReturnStatement))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeNamespace))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeNamespaceCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeNamespaceImport))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeNamespaceImportCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeObject))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeObjectCreateExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeParameterDeclarationExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeParameterDeclarationExpressionCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodePrimitiveExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodePropertyReferenceExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodePropertySetValueReferenceExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeRegionDirective))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeRegionMode))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeRemoveEventStatement))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeSnippetCompileUnit))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeSnippetExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeSnippetStatement))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeSnippetTypeMember))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeStatement))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeStatementCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeThisReferenceExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeThrowExceptionStatement))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeTryCatchFinallyStatement))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeTypeConstructor))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeTypeDeclaration))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeTypeDeclarationCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeTypeDelegate))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeTypeMember))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeTypeMemberCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeTypeOfExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeTypeParameter))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeTypeParameterCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeTypeReference))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeTypeReferenceCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeTypeReferenceExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeTypeReferenceOptions))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeVariableDeclarationStatement))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.CodeVariableReferenceExpression))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.CodeCompiler))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.CodeDomProvider))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.CodeGenerator))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.CodeGeneratorOptions))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.CodeParser))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.CompilerError))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.CompilerErrorCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.CompilerInfo))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.CompilerParameters))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.CompilerResults))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.Executor))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.GeneratorSupport))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.ICodeCompiler))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.ICodeGenerator))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.ICodeParser))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.LanguageOptions))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.Compiler.TempFileCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.FieldDirection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.CodeDom.MemberAttributes))]
