// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
// ------------------------------------------------------------------------------
// Changes to this file must follow the http://aka.ms/api-review process.
// ------------------------------------------------------------------------------
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Reflection.AssemblyTitle("System.IO")]
[assembly: System.Reflection.AssemblyDescription("System.IO")]
[assembly: System.Reflection.AssemblyDefaultAlias("System.IO")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("Microsoft® .NET Framework")]
[assembly: System.Reflection.AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersion("4.6.24705.01")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.6.24705.01. Commit Hash: 4d1af962ca0fede10beb01d197367c2f90e92c97")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: System.Reflection.AssemblyMetadata("Serviceable", "True")]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.BinaryReader))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.BinaryWriter))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.BufferedStream))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.EndOfStreamException))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.FileNotFoundException))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.InvalidDataException))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.IOException))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.MemoryStream))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.SeekOrigin))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Stream))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.StreamReader))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.StreamWriter))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.StringReader))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.StringWriter))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.TextReader))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.TextWriter))]
