parameters:
  # Agent OS identifier and used as job name
- name: agentOs
  type: string

  # Job name
- name: jobName
  type: string


jobs:
- template: common/templates/job/job.yml
  parameters:
    # Set up the name of the job.
    name: ${{ parameters.agentOs }}_${{ parameters.jobName }}
    enablePublishBuildArtifacts: true
    artifacts:
        publish:
          artifacts: true
          manifests: true
    enablePublishTestResults: true
    ## Set up the pool/machine info to be used based on the Agent OS
    ${{ if eq(parameters.agentOs, 'Windows_NT') }}:
      pool:
          vmImage: windows-latest
    ${{ if eq(parameters.agentOs, 'Linux') }}:
      pool:
          vmImage: ubuntu-latest
    steps:
    - checkout: self
      clean: true
    - ${{ if eq(parameters.agentOs, 'Windows_NT') }}:
      - script: $(Build.SourcesDirectory)/build.cmd
                  -test
        displayName: Windows NT Tests

    - ${{ if eq(parameters.agentOs, 'Linux') }}:
      - script: $(Build.SourcesDirectory)/build.sh
                  --test
        displayName: Linux Tests
