parameters:
  # Agent OS identifier and used as job name
- name: agentOs
  type: string

  # Build configuration (Debug, Release)
- name: buildConfiguration
  type: string
  values:
  - Debug
  - Release

jobs:
- template: common/templates/job/job.yml
  parameters:
    # Set up the name of the job.
    name: ${{ parameters.agentOs }}_GenerateScript_Tests
    ## Set up the pool/machine info to be used based on the Agent OS
    ${{ if eq(parameters.agentOs, 'Windows_NT') }}:
      pool:
          vmImage: windows-latest
    ${{ if eq(parameters.agentOs, 'Linux') }}:
      pool:
          vmImage: ubuntu-latest
    steps:
    - checkout: self
      clean: true
    - ${{ if eq(parameters.agentOs, 'Windows_NT') }}:
      - script: $(Build.SourcesDirectory)/build.cmd
                  -test
        displayName: Windows NT GenerateScript Tests

    - ${{ if eq(parameters.agentOs, 'Linux') }}:
      - script: $(Build.SourcesDirectory)/build.sh
                  --test
        displayName: Linux GenerateScript Tests
    - task: PublishTestResults@2
      displayName: Publish Test Results
      inputs:
        testRunner: xUnit
        testResultsFiles: 'artifacts/TestResults/${{ parameters.buildConfiguration }}/*.xml'
        testRunTitle: '$(agentOs)_GenerateScript_tests'
        configuration: '${{ parameters.buildConfiguration }}'
      condition: always()