// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
// ------------------------------------------------------------------------------
// Changes to this file must follow the http://aka.ms/api-review process.
// ------------------------------------------------------------------------------
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Reflection.AssemblyDefaultAlias("Microsoft.Win32.SystemEvents")]
[assembly: System.Reflection.AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: System.Reflection.AssemblyMetadata("Serviceable", "True")]
[assembly: System.Reflection.AssemblyMetadata("PreferInbox", "True")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: System.Reflection.AssemblyDescription("Microsoft.Win32.SystemEvents")]
[assembly: System.Reflection.AssemblyFileVersion("4.700.19.56404")]
[assembly: System.Reflection.AssemblyInformationalVersion("3.1.0+0f7f38c4fd323b26da10cce95f857f77f0f09b48")]
[assembly: System.Reflection.AssemblyProduct("Microsoft® .NET Core")]
[assembly: System.Reflection.AssemblyTitle("Microsoft.Win32.SystemEvents")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.PowerModeChangedEventArgs))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.PowerModeChangedEventHandler))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.PowerModes))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.SessionEndedEventArgs))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.SessionEndedEventHandler))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.SessionEndingEventArgs))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.SessionEndingEventHandler))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.SessionEndReasons))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.SessionSwitchEventArgs))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.SessionSwitchEventHandler))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.SessionSwitchReason))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.SystemEvents))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.TimerElapsedEventArgs))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.TimerElapsedEventHandler))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.UserPreferenceCategory))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.UserPreferenceChangedEventArgs))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.UserPreferenceChangedEventHandler))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.UserPreferenceChangingEventArgs))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.UserPreferenceChangingEventHandler))]
