parameters:
  # This template adds arcade-powered source-build to CI. The template produces a server job with a
  # default ID 'Source_Build_Complete' to put in a dependency list if necessary.

  # Specifies the prefix for source-build jobs added to pipeline. Use this if disambiguation is
  # necessary. This also changes the ID of 'Source_Build_Complete'.
  jobNamePrefix: 'Source_Build'

  # Specifies the build script to invoke to perform the build in the repo. The default should work
  # for typical Arcade repositories, but this is customizable for difficult situations.
  buildScript: './build.sh'

  # Defines the platforms on which to run build jobs. By default, one job on a linux-x64 machine,
  # suitable for managed-only repositories. This is an array of objects with these properties:
  #
  # name: ''
  #   The name of the job, included in the ID.
  # targetRID: ''
  #   The name of the target RID to use, instead of the one auto-detected by Arcade.
  # nonPortable: false
  #   Enables non-portable mode. This means a more specific RID (e.g. fedora.32-x64 rather than
  #   linux-x64), and compiling against distro-provided packages rather than portable ones.
  # container: ''
  #   A container to use. Runs in docker.
  # pool: {}
  #   A pool to use. Runs directly on an agent.
  # jobProperties: {}
  #   A list of job properties to inject at the top level, for potential extensibility beyond
  #   container and pool.
  platforms:
  - name: 'Managed'
    container: 'mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-3e800f1-20190501005343'

jobs:

- job: ${{ parameters.jobNamePrefix }}_Complete
  displayName: Source-Build Complete
  pool: server
  dependsOn:
  - ${{ each platform in parameters.platforms }}:
    - ${{ parameters.jobNamePrefix }}_${{ platform.name }}

- ${{ each platform in parameters.platforms }}:
  - job: ${{ parameters.jobNamePrefix }}_${{ platform.name }}
    displayName: Source-Build (${{ platform.name }})

    ${{ each property in platform.jobProperties }}:
      ${{ property.key }}: ${{ property.value }}

    ${{ if ne(platform.container, '') }}:
      container: ${{ platform.container }}
    ${{ if ne(platform.pool, '') }}:
      pool: ${{ platform.pool }}

    workspace:
      clean: all

    variables:
    - name: _BuildConfig
      value: Release
    - name: _InternalBuildArgs
      value: ''
    - name: _TargetRidArgs
      value: ''
    - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
      - name: _InternalBuildArgs
        value: >-
          /p:DotNetPublishUsingPipelines=true
          /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
    - ${{ if ne(platform.targetRID, '') }}:
      - name: _TargetRidArgs
        value: /p:TargetRid=${{ platform.targetRID }}

    steps:
    - script: |
        set -x
        df -h
        ${{ parameters.buildScript }} --ci \
          --configuration $(_BuildConfig) \
          --restore --build --pack --publish \
          $(_InternalBuildArgs) \
          $(_TargetRidArgs) \
          /p:SourceBuildNonPortable=${{ platform.nonPortable }} \
          /p:ArcadeBuildFromSource=true
      displayName: Build

    # Upload build logs for diagnosis.
    - task: CopyFiles@2
      displayName: Prepare BuildLogs staging directory
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          **/*.log
          **/*.binlog
          artifacts/source-build/self/prebuilt-report/**
        TargetFolder: '$(Build.StagingDirectory)/BuildLogs'
        CleanTargetFolder: true
      continueOnError: true
      condition: succeededOrFailed()

    - task: PublishPipelineArtifact@1
      displayName: Publish BuildLogs
      inputs:
        targetPath: '$(Build.StagingDirectory)/BuildLogs'
        artifactName: BuildLogs_SourceBuild_${{ platform.name }}_Attempt$(System.JobAttempt)
      continueOnError: true
      condition: succeededOrFailed()
