parameters:
  engCommonTemplatesDir: ''

stages:
- stage: build
  displayName: Build
  jobs:
  - template: ${{ parameters.engCommonTemplatesDir }}/jobs/jobs.yml
    parameters:
      enablePublishUsingPipelines: true
      enablePublishBuildArtifacts: true
      enablePublishBuildAssets: true
      artifacts:
        publish:
          artifacts: true
          manifests: true
      enableSourceBuild: true
# Based on - https://github.com/dotnet/arcade/blob/9b3f304c7bc9fd4d11be9ca0b466b83e98d2a191/Documentation/CorePackages/Publishing.md#moving-away-from-the-legacy-pushtoblobfeed-task
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: ${{ parameters.engCommonTemplatesDir }}/post-build/post-build.yml
    parameters:
      publishingInfraVersion: 3
      enableSourceLinkValidation: true
      #Nuget and Signing Validation are not needed as we only produce a transport package.
      enableSigningValidation: false
      enableNugetValidation: false
